### PR TITLE
Fixes #255: Added check for db instance in getClassDbDriverName()

### LINKED ISSUE #255: Getting unknown property: yii\mongodb\Connection::driverName
### What steps will reproduce the problem?

Generate CRUD with `yii\mongodb\ActiveRecord` model

### What's expected?

CRUD generated

### What do you get instead?

Exception: Getting unknown property: yii\mongodb\Connection::driverName

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11
| PHP version     | *
| Operating system | *

Issue migration from https://github.com/yiisoft/yii2-mongodb/issues/191
Problem is caused by recent change intoduced at https://github.com/yiisoft/yii2-gii/pull/244

### PR DESCRIPTION
**Pull request by MKiselev**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #255

### CODE REVIEW

File: generators/crud/Generator.php [hunk 1]
```diff
@@ -552,12 +552,14 @@ public function getColumnNames()
...
+     * In case db is not instance of \yii\db\Connection empty string will be returned.
      * @since 2.0.6
      */
     protected function getClassDbDriverName()
     {
         /* @var $class ActiveRecord */
         $class = $this->modelClass;
-        return $class::getDb()->driverName;
+        $db = $class::getDb();
+        return $db instanceof \yii\db\Connection ? $db->driverName : '';
```
Comment (arogachev) [inline generators/crud/Generator.php]: Why empty string and not `null` for example? Also, unit tests are strict requirement to all framework core related PRs, but they are optional for extensions like Gii? Did I understand that correctly? Maybe because it's hard to test different extensions together like Gii and MongoDB?

Comment (MKiselev) [inline generators/crud/Generator.php]: @arogachev

>Why empty string and not null for example?

Because at night I was think which the driver name can be null when connection is not set :simple_smile:

> Also, unit tests are strict requirement to all framework core related PRs, but they are optional for extensions like Gii? Did I understand that correctly?

Yep.

> Maybe because it's hard to test different extensions together like Gii and MongoDB?

Good idea, but I very weak in the writing tests 👎

Comment (arogachev) [inline generators/crud/Generator.php]: @MKiselev The question about unit tests was addressed more to core developers rather than you since I'm not fully familiar with rules for accepting PRs for extensions. @samdark, can you shed some light to it?

> but I very weak in the writing tests.

No worries, any help is appreciated.

Comment (MKiselev) [inline generators/crud/Generator.php]: @arogachev 

> No worries, any help is appreciated.

Yep. But I understand the importance of tests. :)

**Comment by samdark** [comment]
Merged. Thanks!
